// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeAutomation.Modules.Finance.Infrastructure.Persistence;

#nullable disable

namespace OfficeAutomation.Migrations.FinanceDb
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260702053323_AddAccountNatureAndVoucherValidationGuards")]
    partial class AddAccountNatureAndVoucherValidationGuards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficeAutomation.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplianceCategory")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StructuredPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("UserContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIP")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber");

                    b.HasIndex("Name");

                    b.ToTable("Employers", (string)null);
                });

            modelBuilder.Entity("OfficeAutomation.Models.HumanCapitalEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PersonnelCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HumanCapitalEmployee");
                });

            modelBuilder.Entity("OfficeAutomation.Models.HumanCapitalSalaryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionTitle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("HumanCapitalSalaryHistory");
                });

            modelBuilder.Entity("OfficeAutomation.Models.HumanCapitalStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("HumanCapitalStatusHistory");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InsuranceEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndWork")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HumanCapitalEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceListId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartWork")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HumanCapitalEmployeeId");

                    b.HasIndex("InsuranceListId");

                    b.ToTable("InsuranceEmployees");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InsuranceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InsuranceLists");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InventoryCounting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateShamsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryCounting");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InventoryCountingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscrepancyQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InventoryCountingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PhysicalQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("SystemQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryCountingId");

                    b.ToTable("InventoryCountingItem");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InventoryOpeningBalanceLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseClosingId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseClosingId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryOpeningBalanceLedger");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateShamsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeadlineDateShamsi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<int?>("FollowUpEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalCodeOrEconomicId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("WarehouseReceiptId")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("InvoiceNumber", "InvoiceType")
                        .IsUnique()
                        .HasDatabaseName("IX_Invoice_Number_Type");

                    b.HasIndex("InvoiceType", "DateShamsi")
                        .HasDatabaseName("IX_Invoice_Type_DateShamsi");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("LineGrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineSubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineVatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("OfficeAutomation.Models.PayrollItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Allowance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("HumanCapitalEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPayable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Overtime")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PayrollListId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HumanCapitalEmployeeId");

                    b.HasIndex("PayrollListId");

                    b.ToTable("PayrollItems");
                });

            modelBuilder.Entity("OfficeAutomation.Models.PayrollList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("PayrollLists");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EconomicCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EconomicCode");

                    b.HasIndex("Name");

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("OfficeAutomation.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClosingRules")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseClosing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClosingDateShamsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ClosingYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("OpeningYear")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseClosing");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseClosingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosingQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseClosingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseClosingId");

                    b.ToTable("WarehouseClosingItem");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseIssuance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateShamsi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DestinationOrDepartment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("IssuanceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseIssuance");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseIssuanceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseIssuanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseIssuanceId");

                    b.ToTable("WarehouseIssuanceItem");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Waybill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DriverCommission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DriverNationalId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DriverPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoadingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetPayToDriver")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("TotalFreightCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehiclePlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WaybillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("WaybillNumber")
                        .IsUnique();

                    b.ToTable("Waybills");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.AccountGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AccountGroups");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBaseCurrency")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.CurrencyExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId", "RateDate")
                        .IsUnique();

                    b.ToTable("CurrencyExchangeRates");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.DetailedAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFloating")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartyType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubsidiaryAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SubsidiaryAccountId");

                    b.HasIndex("PartyType", "ExternalReference");

                    b.ToTable("DetailedAccounts");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.FiscalPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId", "PeriodNumber")
                        .IsUnique();

                    b.HasIndex("FiscalYearId", "StartDate", "EndDate");

                    b.ToTable("FiscalPeriods");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("YearName")
                        .IsUnique();

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("FiscalYears");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.FloatingDetailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Type", "Name");

                    b.ToTable("FloatingDetailAccounts");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.GeneralAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NoControl");

                    b.HasKey("Id");

                    b.HasIndex("AccountGroupId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GeneralAccounts");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.JournalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JournalTypes");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsFloatingDetail")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("GeneralAccountId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("NoControl");

                    b.Property<string>("SystemKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GeneralAccountId");

                    b.HasIndex("SystemKey")
                        .IsUnique();

                    b.ToTable("SubsidiaryAccounts");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccountFloatingDetail", b =>
                {
                    b.Property<int>("SubsidiaryAccountId")
                        .HasColumnType("int");

                    b.Property<Guid>("FloatingDetailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubsidiaryAccountId", "FloatingDetailAccountId");

                    b.HasIndex("FloatingDetailAccountId");

                    b.ToTable("SubsidiaryAccountFloatingDetails");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.VoucherHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<int>("JournalTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PostingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<int?>("ReversalOfVoucherHeaderId")
                        .HasColumnType("int");

                    b.Property<int?>("ReversedByVoucherHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("TotalCredits")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebits")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VoucherNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.HasIndex("PostingStatus");

                    b.HasIndex("ReversalOfVoucherHeaderId")
                        .IsUnique()
                        .HasFilter("[ReversalOfVoucherHeaderId] IS NOT NULL");

                    b.HasIndex("VoucherDate");

                    b.HasIndex("FiscalYearId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("FiscalYearId", "VoucherDate");

                    b.HasIndex("FiscalYearId", "VoucherNumber");

                    b.HasIndex("JournalTypeId", "VoucherDate");

                    b.HasIndex("Status", "VoucherDate", "TotalDebits", "TotalCredits");

                    b.ToTable("VoucherHeaders");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.VoucherLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CurrencyId");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DetailedAccountId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("CurrencyRate");

                    b.Property<Guid?>("FloatingDetailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ForeignAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Narration")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("SubsidiaryAccountId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherHeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DetailedAccountId");

                    b.HasIndex("FloatingDetailAccountId");

                    b.HasIndex("SubsidiaryAccountId");

                    b.HasIndex("SubsidiaryAccountId", "FloatingDetailAccountId");

                    b.HasIndex("VoucherHeaderId", "DisplayOrder");

                    b.ToTable("VoucherLines");
                });

            modelBuilder.Entity("OfficeAutomation.Models.HumanCapitalSalaryHistory", b =>
                {
                    b.HasOne("OfficeAutomation.Models.HumanCapitalEmployee", "Employee")
                        .WithMany("SalaryHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OfficeAutomation.Models.HumanCapitalStatusHistory", b =>
                {
                    b.HasOne("OfficeAutomation.Models.HumanCapitalEmployee", "Employee")
                        .WithMany("StatusHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InsuranceEmployee", b =>
                {
                    b.HasOne("OfficeAutomation.Models.HumanCapitalEmployee", "HumanCapitalEmployee")
                        .WithMany()
                        .HasForeignKey("HumanCapitalEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OfficeAutomation.Models.InsuranceList", "InsuranceList")
                        .WithMany("Employees")
                        .HasForeignKey("InsuranceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanCapitalEmployee");

                    b.Navigation("InsuranceList");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InventoryCounting", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Warehouse", "Warehouse")
                        .WithMany("Countings")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InventoryCountingItem", b =>
                {
                    b.HasOne("OfficeAutomation.Models.InventoryCounting", "InventoryCounting")
                        .WithMany("Items")
                        .HasForeignKey("InventoryCountingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryCounting");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InventoryOpeningBalanceLedger", b =>
                {
                    b.HasOne("OfficeAutomation.Models.WarehouseClosing", "WarehouseClosing")
                        .WithMany()
                        .HasForeignKey("WarehouseClosingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.Warehouse", "Warehouse")
                        .WithMany("OpeningLedgers")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");

                    b.Navigation("WarehouseClosing");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Invoice", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Employer", "Employer")
                        .WithMany("Invoices")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InvoiceItem", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("OfficeAutomation.Models.PayrollItem", b =>
                {
                    b.HasOne("OfficeAutomation.Models.HumanCapitalEmployee", "HumanCapitalEmployee")
                        .WithMany()
                        .HasForeignKey("HumanCapitalEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OfficeAutomation.Models.PayrollList", "PayrollList")
                        .WithMany("Items")
                        .HasForeignKey("PayrollListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanCapitalEmployee");

                    b.Navigation("PayrollList");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseClosing", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Warehouse", "Warehouse")
                        .WithMany("Closings")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseClosingItem", b =>
                {
                    b.HasOne("OfficeAutomation.Models.WarehouseClosing", "WarehouseClosing")
                        .WithMany("Items")
                        .HasForeignKey("WarehouseClosingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarehouseClosing");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseIssuance", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Employer", "Employer")
                        .WithMany("Issuances")
                        .HasForeignKey("EmployerId");

                    b.HasOne("OfficeAutomation.Models.Warehouse", "Warehouse")
                        .WithMany("Issuances")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseIssuanceItem", b =>
                {
                    b.HasOne("OfficeAutomation.Models.WarehouseIssuance", "WarehouseIssuance")
                        .WithMany("Items")
                        .HasForeignKey("WarehouseIssuanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarehouseIssuance");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.CurrencyExchangeRate", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.Currency", "Currency")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.DetailedAccount", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccount", "SubsidiaryAccount")
                        .WithMany("DetailedAccounts")
                        .HasForeignKey("SubsidiaryAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SubsidiaryAccount");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.FiscalPeriod", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.FiscalYear", "FiscalYear")
                        .WithMany("FiscalPeriods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.GeneralAccount", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.AccountGroup", "AccountGroup")
                        .WithMany("GeneralAccounts")
                        .HasForeignKey("AccountGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountGroup");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccount", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.GeneralAccount", "GeneralAccount")
                        .WithMany("SubsidiaryAccounts")
                        .HasForeignKey("GeneralAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneralAccount");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccountFloatingDetail", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.FloatingDetailAccount", "FloatingDetailAccount")
                        .WithMany("SubsidiaryAccountLinks")
                        .HasForeignKey("FloatingDetailAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccount", "SubsidiaryAccount")
                        .WithMany("FloatingDetailLinks")
                        .HasForeignKey("SubsidiaryAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FloatingDetailAccount");

                    b.Navigation("SubsidiaryAccount");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.VoucherHeader", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.FiscalYear", "FiscalYear")
                        .WithMany("VoucherHeaders")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.JournalType", "JournalType")
                        .WithMany("Vouchers")
                        .HasForeignKey("JournalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.VoucherHeader", "ReversalOfVoucherHeader")
                        .WithOne("ReversedByVoucherHeader")
                        .HasForeignKey("OfficeAutomation.Modules.Finance.Domain.VoucherHeader", "ReversalOfVoucherHeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FiscalYear");

                    b.Navigation("JournalType");

                    b.Navigation("ReversalOfVoucherHeader");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.VoucherLine", b =>
                {
                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.Currency", "Currency")
                        .WithMany("VoucherLines")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.DetailedAccount", "DetailedAccount")
                        .WithMany("VoucherLines")
                        .HasForeignKey("DetailedAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.FloatingDetailAccount", "FloatingDetailAccount")
                        .WithMany("VoucherLines")
                        .HasForeignKey("FloatingDetailAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccount", "SubsidiaryAccount")
                        .WithMany("VoucherLines")
                        .HasForeignKey("SubsidiaryAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Modules.Finance.Domain.VoucherHeader", "VoucherHeader")
                        .WithMany("Lines")
                        .HasForeignKey("VoucherHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("DetailedAccount");

                    b.Navigation("FloatingDetailAccount");

                    b.Navigation("SubsidiaryAccount");

                    b.Navigation("VoucherHeader");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Employer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Issuances");
                });

            modelBuilder.Entity("OfficeAutomation.Models.HumanCapitalEmployee", b =>
                {
                    b.Navigation("SalaryHistories");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InsuranceList", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("OfficeAutomation.Models.InventoryCounting", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OfficeAutomation.Models.PayrollList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Warehouse", b =>
                {
                    b.Navigation("Closings");

                    b.Navigation("Countings");

                    b.Navigation("Issuances");

                    b.Navigation("OpeningLedgers");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseClosing", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WarehouseIssuance", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.AccountGroup", b =>
                {
                    b.Navigation("GeneralAccounts");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.Currency", b =>
                {
                    b.Navigation("ExchangeRates");

                    b.Navigation("VoucherLines");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.DetailedAccount", b =>
                {
                    b.Navigation("VoucherLines");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.FiscalYear", b =>
                {
                    b.Navigation("FiscalPeriods");

                    b.Navigation("VoucherHeaders");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.FloatingDetailAccount", b =>
                {
                    b.Navigation("SubsidiaryAccountLinks");

                    b.Navigation("VoucherLines");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.GeneralAccount", b =>
                {
                    b.Navigation("SubsidiaryAccounts");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.JournalType", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.SubsidiaryAccount", b =>
                {
                    b.Navigation("DetailedAccounts");

                    b.Navigation("FloatingDetailLinks");

                    b.Navigation("VoucherLines");
                });

            modelBuilder.Entity("OfficeAutomation.Modules.Finance.Domain.VoucherHeader", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("ReversedByVoucherHeader");
                });
#pragma warning restore 612, 618
        }
    }
}
