// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeAutomation.Modules.Workflow.Infrastructure.Persistence;

#nullable disable

namespace OfficeAutomation.Migrations.WorkflowDb
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfficeAutomation.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataAccessScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("OfficeAutomation.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplianceCategory")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StructuredPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("UserContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIP")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OfficeAutomation.Models.ConnectorDeadLetterMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ConnectorName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastRetriedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "FailedAt");

                    b.ToTable("ConnectorDeadLetterMessages");
                });

            modelBuilder.Entity("OfficeAutomation.Models.ConnectorExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ConnectorName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorName", "ExecutedAt");

                    b.ToTable("ConnectorExecutionLogs");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OfficeAutomation.Models.DocumentArchiveItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPreviewable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderLegalHold")
                        .HasColumnType("bit");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RelatedModule")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsUnderLegalHold");

                    b.ToTable("DocumentArchiveItems");
                });

            modelBuilder.Entity("OfficeAutomation.Models.DocumentSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateSubject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CertificateThumbprint")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("SHA256");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SignatureKeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SignatureValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SignerDisplayName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SignerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SigningReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("WorkflowDecisionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayloadHash");

                    b.HasIndex("SignerUserId");

                    b.HasIndex("WorkflowDecisionId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("DocumentType", "DocumentId", "SignedAt");

                    b.ToTable("DocumentSignatures");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentWorkflowStep")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalReceiverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkflowCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ReplyToLetterId")
                        .HasColumnType("int");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("FinalReceiverId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ReplyToLetterId");

                    b.HasIndex("SenderId");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SourceEntityId")
                        .HasColumnType("int");

                    b.Property<string>("SourceEntityType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SourceModule")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OfficeAutomation.Models.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAt");

                    b.HasIndex("Status", "LockedUntil", "OccurredAt");

                    b.HasIndex("TenantId", "Status", "LockedUntil", "OccurredAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("OfficeAutomation.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveEnvironment")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ApplicationTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("bit");

                    b.Property<string>("SystemLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("OfficeAutomation.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("CanAccessFinance")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAccessHumanCapital")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAccessSystemSettings")
                        .HasColumnType("bit");

                    b.Property<bool>("CanAccessWarehouse")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentManagerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("WorkflowInstanceId", "OccurredAt");

                    b.ToTable("WorkflowActionLogs");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("WorkflowDecisionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("WorkflowDecisionId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("WorkflowInstanceId", "UploadedAt");

                    b.ToTable("WorkflowAttachments");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowCaseTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SubCaseInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubCaseInstanceId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("WorkflowInstanceId", "Status", "TaskType");

                    b.ToTable("WorkflowCaseTasks");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("WorkflowInstanceId", "CreatedAt");

                    b.ToTable("WorkflowComments");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecidedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SignatureText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("WorkflowInstanceId", "DecidedAt");

                    b.ToTable("WorkflowDecisions");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowDefinitionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeploymentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Stable");

                    b.Property<string>("DeploymentRing")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("RollbackOfVersionId")
                        .HasColumnType("int");

                    b.Property<int>("TrafficPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType", "Version")
                        .IsUnique();

                    b.HasIndex("DocumentType", "IsActive", "EffectiveFrom");

                    b.ToTable("WorkflowDefinitionVersions");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowDelegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId");

                    b.HasIndex("FromUserId", "StartsAt", "EndsAt");

                    b.ToTable("WorkflowDelegations");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowEscalationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EscalatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EscalatedToRoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EscalatedToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NewSlaState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PreviousSlaState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscalatedToRoleId");

                    b.HasIndex("EscalatedToUserId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("WorkflowEscalationEvents");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("RetriedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("WorkflowInstanceId", "IsResolved", "OccurredAt");

                    b.ToTable("WorkflowIncidents");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CurrentAssigneeDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentAssigneeRoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentAssigneeUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CurrentStepNumber")
                        .HasColumnType("int");

                    b.Property<int?>("DefinitionVersionId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastActionAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ParentWorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SlaState")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StartedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAssigneeDepartmentId");

                    b.HasIndex("CurrentAssigneeRoleId");

                    b.HasIndex("DefinitionVersionId");

                    b.HasIndex("ParentWorkflowInstanceId");

                    b.HasIndex("StartedByUserId");

                    b.HasIndex("DefinitionVersionId", "Status");

                    b.HasIndex("DocumentType", "DocumentId")
                        .IsUnique();

                    b.HasIndex("Status", "DueAt");

                    b.HasIndex("CurrentAssigneeUserId", "Status", "DueAt");

                    b.HasIndex("Status", "SlaState", "DueAt");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDelegation")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowReturn")
                        .HasColumnType("bit");

                    b.Property<int?>("ApproverDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ApproverRoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApproverUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignmentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("EscalationHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SlaHours")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverDepartmentId");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("DocumentType", "StepNumber");

                    b.ToTable("WorkflowRoutes");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("AssigneeRoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssigneeUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NextStepKey")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("StepDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeDepartmentId");

                    b.HasIndex("AssigneeRoleId");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("StepDefinitionId", "FieldName", "Operator");

                    b.ToTable("WorkflowRules");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowSlaJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("Status", "ScheduledFor");

                    b.HasIndex("WorkflowStepId", "Status");

                    b.ToTable("WorkflowSlaJobs");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedRoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssignmentMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DelegatedFromUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ReturnedFromStepNumber")
                        .HasColumnType("int");

                    b.Property<string>("SlaState")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StepKey")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("StepName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DelegatedFromUserId");

                    b.HasIndex("ReadAt", "CreatedAt");

                    b.HasIndex("WorkflowInstanceId", "StepNumber");

                    b.HasIndex("AssignedDepartmentId", "Status", "DueAt");

                    b.HasIndex("AssignedRoleId", "Status", "DueAt");

                    b.HasIndex("AssignedToUserId", "Status", "DueAt");

                    b.HasIndex("WorkflowInstanceId", "Status", "DueAt");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowStepDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignmentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("User");

                    b.Property<int>("DefinitionVersionId")
                        .HasColumnType("int");

                    b.Property<int>("EscalationHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(48);

                    b.Property<int>("SlaHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(24);

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionVersionId", "StepKey")
                        .IsUnique();

                    b.HasIndex("DefinitionVersionId", "StepOrder")
                        .IsUnique();

                    b.ToTable("WorkflowStepDefinitions");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowTransitionEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("FromStepNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StationKey")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("StationName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ToStepNumber")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("StationKey", "OccurredAt");

                    b.HasIndex("WorkflowInstanceId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("WorkflowTransitionEvents");
                });

            modelBuilder.Entity("OfficeAutomation.Models.DocumentArchiveItem", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("OfficeAutomation.Models.DocumentSignature", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "SignerUser")
                        .WithMany()
                        .HasForeignKey("SignerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowDecision", "WorkflowDecision")
                        .WithMany("DocumentSignatures")
                        .HasForeignKey("WorkflowDecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("DocumentSignatures")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignerUser");

                    b.Navigation("WorkflowDecision");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Leave", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Letter", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "FinalReceiver")
                        .WithMany()
                        .HasForeignKey("FinalReceiverId");

                    b.HasOne("OfficeAutomation.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.Letter", "ReplyToLetter")
                        .WithMany()
                        .HasForeignKey("ReplyToLetterId");

                    b.HasOne("OfficeAutomation.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinalReceiver");

                    b.Navigation("Receiver");

                    b.Navigation("ReplyToLetter");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("OfficeAutomation.Models.Notification", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowActionLog", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("ActionLogs")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId");

                    b.Navigation("ActorUser");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowAttachment", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowDecision", "WorkflowDecision")
                        .WithMany()
                        .HasForeignKey("WorkflowDecisionId");

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Attachments")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId");

                    b.Navigation("UploadedByUser");

                    b.Navigation("WorkflowDecision");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowCaseTask", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "SubCaseInstance")
                        .WithMany()
                        .HasForeignKey("SubCaseInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("CaseTasks")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("CaseTasks")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("SubCaseInstance");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowComment", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Comments")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId");

                    b.Navigation("AuthorUser");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowDecision", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Decisions")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DecidedByUser");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowDelegation", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowEscalationEvent", b =>
                {
                    b.HasOne("OfficeAutomation.Models.ApplicationRole", "EscalatedToRole")
                        .WithMany()
                        .HasForeignKey("EscalatedToRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "EscalatedToUser")
                        .WithMany()
                        .HasForeignKey("EscalatedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Escalations")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId");

                    b.Navigation("EscalatedToRole");

                    b.Navigation("EscalatedToUser");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowIncident", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Incidents")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ActorUser");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowInstance", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Department", "CurrentAssigneeDepartment")
                        .WithMany()
                        .HasForeignKey("CurrentAssigneeDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.ApplicationRole", "CurrentAssigneeRole")
                        .WithMany()
                        .HasForeignKey("CurrentAssigneeRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "CurrentAssigneeUser")
                        .WithMany()
                        .HasForeignKey("CurrentAssigneeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.WorkflowDefinitionVersion", "DefinitionVersion")
                        .WithMany("WorkflowInstances")
                        .HasForeignKey("DefinitionVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "ParentWorkflowInstance")
                        .WithMany("SubCases")
                        .HasForeignKey("ParentWorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "StartedByUser")
                        .WithMany()
                        .HasForeignKey("StartedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentAssigneeDepartment");

                    b.Navigation("CurrentAssigneeRole");

                    b.Navigation("CurrentAssigneeUser");

                    b.Navigation("DefinitionVersion");

                    b.Navigation("ParentWorkflowInstance");

                    b.Navigation("StartedByUser");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowRoute", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Department", "ApproverDepartment")
                        .WithMany()
                        .HasForeignKey("ApproverDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.ApplicationRole", "ApproverRole")
                        .WithMany()
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApproverDepartment");

                    b.Navigation("ApproverRole");

                    b.Navigation("ApproverUser");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowRule", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Department", "AssigneeDepartment")
                        .WithMany()
                        .HasForeignKey("AssigneeDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.ApplicationRole", "AssigneeRole")
                        .WithMany()
                        .HasForeignKey("AssigneeRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "AssigneeUser")
                        .WithMany()
                        .HasForeignKey("AssigneeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.WorkflowStepDefinition", "StepDefinition")
                        .WithMany("Rules")
                        .HasForeignKey("StepDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssigneeDepartment");

                    b.Navigation("AssigneeRole");

                    b.Navigation("AssigneeUser");

                    b.Navigation("StepDefinition");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowSlaJob", b =>
                {
                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("SlaJobs")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("SlaJobs")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowStep", b =>
                {
                    b.HasOne("OfficeAutomation.Models.Department", "AssignedDepartment")
                        .WithMany()
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.ApplicationRole", "AssignedRole")
                        .WithMany()
                        .HasForeignKey("AssignedRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.User", "DelegatedFromUser")
                        .WithMany()
                        .HasForeignKey("DelegatedFromUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDepartment");

                    b.Navigation("AssignedRole");

                    b.Navigation("AssignedToUser");

                    b.Navigation("DelegatedFromUser");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowStepDefinition", b =>
                {
                    b.HasOne("OfficeAutomation.Models.WorkflowDefinitionVersion", "DefinitionVersion")
                        .WithMany("StepDefinitions")
                        .HasForeignKey("DefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefinitionVersion");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowTransitionEvent", b =>
                {
                    b.HasOne("OfficeAutomation.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OfficeAutomation.Models.WorkflowInstance", "WorkflowInstance")
                        .WithMany("TransitionEvents")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OfficeAutomation.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("TransitionEvents")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowDecision", b =>
                {
                    b.Navigation("DocumentSignatures");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowDefinitionVersion", b =>
                {
                    b.Navigation("StepDefinitions");

                    b.Navigation("WorkflowInstances");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowInstance", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("Attachments");

                    b.Navigation("CaseTasks");

                    b.Navigation("Comments");

                    b.Navigation("Decisions");

                    b.Navigation("DocumentSignatures");

                    b.Navigation("Escalations");

                    b.Navigation("Incidents");

                    b.Navigation("SlaJobs");

                    b.Navigation("Steps");

                    b.Navigation("SubCases");

                    b.Navigation("TransitionEvents");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowStep", b =>
                {
                    b.Navigation("CaseTasks");

                    b.Navigation("SlaJobs");

                    b.Navigation("TransitionEvents");
                });

            modelBuilder.Entity("OfficeAutomation.Models.WorkflowStepDefinition", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
